FROM mcr.microsoft.com/playwright:v1.57.0-noble

WORKDIR /app

RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

COPY package*.json bun.lock* /app/

RUN bun install

COPY ./ /app/

ARG VITE_API_URL
