FROM mcr.microsoft.com/playwright:v1.62.1-noble

WORKDIR /app

COPY --from=oven/bun:latest /usr/local/bin/bun /usr/local/bin/bun

COPY package.json bun.lock /app/

COPY frontend/package.json /app/frontend/

WORKDIR /app/frontend

RUN bun install

COPY ./frontend /app/frontend
