// This file is auto-generated by @hey-api/openapi-ts

export const AnswerPublicSchema = {
    properties: {
        response: {
            type: 'string',
            title: 'Response'
        },
        is_correct: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Correct'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        question_id: {
            type: 'string',
            format: 'uuid',
            title: 'Question Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        explanation: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ExplanationOutput'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['response', 'id', 'question_id', 'created_at', 'updated_at'],
    title: 'AnswerPublic'
} as const;

export const AnswerUpdateSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        question_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Id'
        },
        response: {
            type: 'string',
            title: 'Response'
        }
    },
    type: 'object',
    required: ['response'],
    title: 'AnswerUpdate'
} as const;

export const Body_documents_create_documentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_documents-create_document'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const DifficultySchema = {
    type: 'string',
    enum: ['easy', 'medium', 'hard'],
    title: 'Difficulty'
} as const;

export const DocumentPublicSchema = {
    properties: {
        filename: {
            type: 'string',
            title: 'Filename'
        },
        s3_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'S3 Url'
        },
        s3_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'S3 Key'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        extracted_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extracted Text'
        },
        status: {
            '$ref': '#/components/schemas/DocumentStatus'
        }
    },
    type: 'object',
    required: ['filename', 'id', 'owner_id', 'status'],
    title: 'DocumentPublic'
} as const;

export const DocumentStatusSchema = {
    type: 'string',
    enum: ['processing', 'ready', 'failed'],
    title: 'DocumentStatus'
} as const;

export const DocumentUpdateSchema = {
    properties: {
        filename: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        },
        s3_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'S3 Url'
        },
        s3_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'S3 Key'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        }
    },
    type: 'object',
    title: 'DocumentUpdate'
} as const;

export const DocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DocumentsPublic'
} as const;

export const ExamAttemptCreateSchema = {
    properties: {
        score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score'
        },
        is_complete: {
            type: 'boolean',
            title: 'Is Complete',
            default: false
        },
        exam_id: {
            type: 'string',
            format: 'uuid',
            title: 'Exam Id'
        },
        answers: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/AnswerUpdate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Answers'
        }
    },
    type: 'object',
    required: ['exam_id'],
    title: 'ExamAttemptCreate'
} as const;

export const ExamAttemptPublicSchema = {
    properties: {
        score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score'
        },
        is_complete: {
            type: 'boolean',
            title: 'Is Complete',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        exam_id: {
            type: 'string',
            format: 'uuid',
            title: 'Exam Id'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        exam: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ExamPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        answers: {
            items: {
                '$ref': '#/components/schemas/AnswerPublic'
            },
            type: 'array',
            title: 'Answers'
        }
    },
    type: 'object',
    required: ['id', 'exam_id', 'completed_at', 'created_at', 'updated_at', 'exam', 'answers'],
    title: 'ExamAttemptPublic'
} as const;

export const ExamPublicSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        duration_minutes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Minutes'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        questions: {
            items: {
                '$ref': '#/components/schemas/QuestionPublic'
            },
            type: 'array',
            title: 'Questions'
        },
        source_document_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Source Document Ids'
        },
        highest_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Highest Score'
        },
        difficulty: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Difficulty'
                },
                {
                    type: 'null'
                }
            ]
        },
        question_types: {
            items: {
                '$ref': '#/components/schemas/QuestionType'
            },
            type: 'array',
            title: 'Question Types'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id', 'created_at'],
    title: 'ExamPublic'
} as const;

export const ExamUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        duration_minutes: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Minutes'
        },
        is_published: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Published'
        }
    },
    type: 'object',
    title: 'ExamUpdate'
} as const;

export const ExamsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExamPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExamsPublic'
} as const;

export const ExplanationOutputSchema = {
    properties: {
        explanation: {
            type: 'string',
            title: 'Explanation'
        },
        key_takeaway: {
            type: 'string',
            title: 'Key Takeaway'
        },
        suggested_review: {
            type: 'string',
            title: 'Suggested Review'
        }
    },
    type: 'object',
    required: ['explanation', 'key_takeaway', 'suggested_review'],
    title: 'ExplanationOutput'
} as const;

export const GenerateQuestionsPublicSchema = {
    properties: {
        num_questions: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Num Questions',
            default: 5
        },
        difficulty: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Difficulty'
                },
                {
                    type: 'null'
                }
            ]
        },
        question_types: {
            items: {
                '$ref': '#/components/schemas/QuestionType'
            },
            type: 'array',
            title: 'Question Types'
        },
        document_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Document Ids'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        }
    },
    type: 'object',
    required: ['document_ids', 'title'],
    title: 'GenerateQuestionsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QuestionPublicSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        },
        type: {
            '$ref': '#/components/schemas/QuestionType'
        },
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Options'
        },
        correct_answer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correct Answer'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['question', 'type', 'options', 'id'],
    title: 'QuestionPublic'
} as const;

export const QuestionTypeSchema = {
    type: 'string',
    enum: ['multiple_choice', 'true_false'],
    title: 'QuestionType'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;