FROM nginx:1

COPY marketing/nginx.conf /etc/nginx/conf.d/default.conf
COPY marketing/index.html /usr/share/nginx/html/index.html
COPY marketing/robots.txt /usr/share/nginx/html/robots.txt
COPY marketing/sitemap.xml /usr/share/nginx/html/sitemap.xml
