"""your_new_changes

Revision ID: 15b7e49466ec
Revises: 6a0826f924e8
Create Date: 2025-02-06 12:56:25.950098

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '15b7e49466ec'
down_revision = '6a0826f924e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
