"""Create qrcode table

Revision ID: 20cc9e9039fd
Revises: 91f6f2bc36a4
Create Date: 2024-11-01 10:17:32.083891

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '20cc9e9039fd'
down_revision = '91f6f2bc36a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
