"""migration added

Revision ID: 36d7ec60e107
Revises: bf1a1316a660
Create Date: 2024-08-03 23:24:23.243748

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36d7ec60e107'
down_revision = 'bf1a1316a660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('email_verified_primary', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('email_verified_secondary', sa.Boolean(), nullable=False))
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'email_verified_secondary')
    op.drop_column('user', 'email_verified_primary')
    op.drop_table('otp_auth')
    # ### end Alembic commands ###
