"""added qr_codes to foodcourt

Revision ID: 375a3d9f95aa
Revises: fe4249d074a6
Create Date: 2024-10-05 07:58:40.774421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '375a3d9f95aa'
down_revision = 'fe4249d074a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
