"""Add created_at to User and Item

Revision ID: 44fc2bbcc925
Revises: 1a31ce608336
Create Date: 2026-01-23 15:42:52.493895

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44fc2bbcc925'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('item', 'created_at')
    # ### end Alembic commands ###
