"""update inventory update  modal

Revision ID: 895c940912d3
Revises: 87867df76bfb
Create Date: 2024-04-28 20:27:51.280731

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '895c940912d3'
down_revision = '87867df76bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
