"""migration added

Revision ID: 8b9a5a7a5fe3
Revises: 5eef61d10886
Create Date: 2024-08-02 23:14:05.552810

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b9a5a7a5fe3'
down_revision = '5eef61d10886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
