"""update inventory update  modal

Revision ID: 8ca20bb4226b
Revises: 4c52939db025
Create Date: 2024-04-28 20:37:19.407805

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ca20bb4226b'
down_revision = '4c52939db025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
