"""Update user mapping

Revision ID: 9396ec22884d
Revises: e49099b0a121
Create Date: 2024-04-28 14:39:45.790506

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9396ec22884d'
down_revision = 'e49099b0a121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
