"""update inventory update  modal

Revision ID: 95fd5e9366f2
Revises: 3324d5db55ab
Create Date: 2024-04-29 06:51:54.298714

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95fd5e9366f2'
down_revision = '3324d5db55ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
