"""update inventory update modal

Revision ID: a4b7803ca038
Revises: bfc78a39381e
Create Date: 2024-04-28 20:09:27.406759

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a4b7803ca038'
down_revision = 'bfc78a39381e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
