"""update inventory update inventory  modal

Revision ID: ba56dbac6f2e
Revises: 217012112ae5
Create Date: 2024-04-29 07:32:07.256962

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba56dbac6f2e'
down_revision = '217012112ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
