"""Add metadata fields to Item

Revision ID: bc408f47ce8b
Revises: 1a31ce608336
Create Date: 2025-06-16 19:13:48.082374

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc408f47ce8b'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('price', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('item', sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('in_featured', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('tries', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('favorites', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('duration', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'favorites')
    op.drop_column('item', 'tries')
    op.drop_column('item', 'rating')
    op.drop_column('item', 'in_featured')
    op.drop_column('item', 'picture')
    op.drop_column('item', 'link')
    op.drop_column('item', 'tags')
    op.drop_column('item', 'category')
    op.drop_column('item', 'type')
    op.drop_column('item', 'difficulty')
    op.drop_column('item', 'price')
    op.drop_column('item', 'location')
    op.drop_column('item', 'duration')
    # ### end Alembic commands ###
