"""add personal best

Revision ID: d9e531296459
Revises: 88f7b2617cf8
Create Date: 2025-06-03 18:29:20.356916

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd9e531296459'
down_revision = '88f7b2617cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalbest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('date_achieved', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_exercise_category'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_workout_id'), table_name='exercise')
    op.drop_constraint(op.f('exercise_workout_id_fkey'), 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'workout', ['workout_id'], ['id'])
    op.drop_index(op.f('ix_userfollow_followed_id'), table_name='userfollow')
    op.drop_index(op.f('ix_userfollow_follower_id'), table_name='userfollow')
    op.drop_index(op.f('ix_workout_is_completed'), table_name='workout')
    op.drop_index(op.f('ix_workout_scheduled_date'), table_name='workout')
    op.drop_index(op.f('ix_workout_user_id'), table_name='workout')
    op.drop_constraint(op.f('workout_user_id_fkey'), 'workout', type_='foreignkey')
    op.create_foreign_key(None, 'workout', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_workoutpost_created_at'), table_name='workoutpost')
    op.drop_index(op.f('ix_workoutpost_user_id'), table_name='workoutpost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workoutpost_user_id'), 'workoutpost', ['user_id'], unique=False)
    op.create_index(op.f('ix_workoutpost_created_at'), 'workoutpost', ['created_at'], unique=False)
    op.drop_constraint(None, 'workout', type_='foreignkey')
    op.create_foreign_key(op.f('workout_user_id_fkey'), 'workout', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_workout_user_id'), 'workout', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_scheduled_date'), 'workout', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_workout_is_completed'), 'workout', ['is_completed'], unique=False)
    op.create_index(op.f('ix_userfollow_follower_id'), 'userfollow', ['follower_id'], unique=False)
    op.create_index(op.f('ix_userfollow_followed_id'), 'userfollow', ['followed_id'], unique=False)
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_workout_id_fkey'), 'exercise', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_exercise_workout_id'), 'exercise', ['workout_id'], unique=False)
    op.create_index(op.f('ix_exercise_category'), 'exercise', ['category'], unique=False)
    op.drop_table('personalbest')
    # ### end Alembic commands ###
