"""Add vietnamese administrative tables

Revision ID: e3b62a02ffd7
Revises: f6a7b8c9d0e1
Create Date: 2026-05-16 21:18:03.060707

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3b62a02ffd7'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrative_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('short_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinces',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_provinces_administrative_unit_id'), 'provinces', ['administrative_unit_id'], unique=False)
    op.create_table('wards',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('province_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_wards_administrative_unit_id'), 'wards', ['administrative_unit_id'], unique=False)
    op.create_index(op.f('ix_wards_province_code'), 'wards', ['province_code'], unique=False)
    op.drop_index(op.f('ix_race_embedding_ivfflat'), table_name='race', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('race_search_vector_idx'), table_name='race', postgresql_using='gin')
    op.drop_column('race', 'search_vector')
    op.drop_constraint(op.f('racetag_name_key'), 'racetag', type_='unique')
    op.drop_constraint(op.f('racetag_slug_key'), 'racetag', type_='unique')
    op.alter_column('userprofile', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('userprofile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('userprofile_user_id_key'), 'userprofile', type_='unique')
    op.alter_column('userraceinteraction', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userraceinteraction', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('userprofile_user_id_key'), 'userprofile', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('userprofile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('userprofile', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('racetag_slug_key'), 'racetag', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('racetag_name_key'), 'racetag', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('race', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, (((((((((COALESCE(name, ''::character varying))::text || ' '::text) || (COALESCE(description, ''::character varying))::text) || ' '::text) || (COALESCE(city, ''::character varying))::text) || ' '::text) || (COALESCE(state, ''::character varying))::text) || ' '::text) || (COALESCE(country, ''::character varying))::text))", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('race_search_vector_idx'), 'race', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_race_embedding_ivfflat'), 'race', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_wards_province_code'), table_name='wards')
    op.drop_index(op.f('ix_wards_administrative_unit_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_provinces_administrative_unit_id'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_table('administrative_units')
    op.drop_table('administrative_regions')
    # ### end Alembic commands ###
