"""create menu_subcategory table

Revision ID: ea33a3e76248
Revises: 3078d16ee962
Create Date: 2024-10-24 23:25:14.486071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea33a3e76248'
down_revision = '3078d16ee962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_subcategory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_alcoholic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_subcategory_id'), 'menu_subcategory', ['id'], unique=False)
    op.add_column('menu_item', sa.Column('subcategory_id', sa.Uuid(), nullable=False))
    op.drop_constraint('menu_item_category_id_fkey', 'menu_item', type_='foreignkey')
    op.create_foreign_key(None, 'menu_item', 'menu_subcategory', ['subcategory_id'], ['id'])
    op.drop_column('menu_item', 'category_id')
    op.drop_column('menu_item', 'sub_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('sub_category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('menu_item', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu_item', type_='foreignkey')
    op.create_foreign_key('menu_item_category_id_fkey', 'menu_item', 'menu_category', ['category_id'], ['id'])
    op.create_foreign_key('menu_item_sub_category_id_fkey', 'menu_item', 'menu_sub_category', ['sub_category_id'], ['id'])
    op.drop_column('menu_item', 'subcategory_id')
    op.create_table('menu_sub_category',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_category.id'], name='menu_sub_category_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='menu_sub_category_pkey')
    )
    op.create_index('ix_menu_sub_category_id', 'menu_sub_category', ['id'], unique=False)
    op.drop_index(op.f('ix_menu_subcategory_id'), table_name='menu_subcategory')
    op.drop_table('menu_subcategory')
    # ### end Alembic commands ###
