"""refine db

Revision ID: f2d6aba28d7d
Revises: 80580dd7587b
Create Date: 2024-12-06 14:59:08.495370

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f2d6aba28d7d'
down_revision = '80580dd7587b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtodo', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('subtodo', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.add_column('todo', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.alter_column('todo', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('todo', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.drop_constraint('todo_user_id_fkey', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key('todo_user_id_fkey', 'todo', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('todo', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('todo', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('todo', 'owner_id')
    op.alter_column('subtodo', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('subtodo', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
