"""Application constants."""

# HTTP Status codes
OK_CODE = 200
CREATED_CODE = 201
BAD_REQUEST_CODE = 400
FORBIDDEN_CODE = 403
NOT_FOUND_CODE = 404
CONFLICT_CODE = 409

# String field lengths
EMAIL_MAX_LENGTH = 255
STRING_MAX_LENGTH = 255
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 40
TOKEN_LENGTH = 32

# Database limits
MAX_MODULE_MEMBERS = 7
MAX_FUNCTION_VARIABLES = 5
MAX_ASSERT_STATEMENTS = 5
MAX_TRY_BODY_LENGTH = 1
MAX_IMPORTED_NAMES = 8
MIN_VARIABLE_NAME_LENGTH = 2
MAX_JONES_COMPLEXITY = 14
MAX_STRING_LITERAL_USAGE = 3
MAX_EXPRESSION_USAGE = 7