/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProfileSetupRouteImport } from './routes/app.profile-setup'
import { Route as AppInsightRankingRiskRouteImport } from './routes/app.insight.ranking-risk'
import { Route as AppInsightGrowthRiskRouteImport } from './routes/app.insight.growth-risk'
import { Route as AppInsightCompetitiveRiskRouteImport } from './routes/app.insight.competitive-risk'
import { Route as AppInsightBrandRiskRouteImport } from './routes/app.insight.brand-risk'
import { Route as AppDashboardPerformanceRouteImport } from './routes/app.dashboard.performance'
import { Route as AppDashboardOverviewRouteImport } from './routes/app.dashboard.overview'
import { Route as AppDashboardDashboardRouteImport } from './routes/app.dashboard.dashboard'
import { Route as AppDashboardCompetitorsRouteImport } from './routes/app.dashboard.competitors'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSetupRoute = AppProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightRankingRiskRoute = AppInsightRankingRiskRouteImport.update({
  id: '/insight/ranking-risk',
  path: '/insight/ranking-risk',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightGrowthRiskRoute = AppInsightGrowthRiskRouteImport.update({
  id: '/insight/growth-risk',
  path: '/insight/growth-risk',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightCompetitiveRiskRoute =
  AppInsightCompetitiveRiskRouteImport.update({
    id: '/insight/competitive-risk',
    path: '/insight/competitive-risk',
    getParentRoute: () => AppRoute,
  } as any)
const AppInsightBrandRiskRoute = AppInsightBrandRiskRouteImport.update({
  id: '/insight/brand-risk',
  path: '/insight/brand-risk',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardPerformanceRoute = AppDashboardPerformanceRouteImport.update({
  id: '/dashboard/performance',
  path: '/dashboard/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardOverviewRoute = AppDashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardDashboardRoute = AppDashboardDashboardRouteImport.update({
  id: '/dashboard/dashboard',
  path: '/dashboard/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardCompetitorsRoute = AppDashboardCompetitorsRouteImport.update({
  id: '/dashboard/competitors',
  path: '/dashboard/competitors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/profile-setup': typeof AppProfileSetupRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/users': typeof AppUsersRoute
  '/app/dashboard/competitors': typeof AppDashboardCompetitorsRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/performance': typeof AppDashboardPerformanceRoute
  '/app/insight/brand-risk': typeof AppInsightBrandRiskRoute
  '/app/insight/competitive-risk': typeof AppInsightCompetitiveRiskRoute
  '/app/insight/growth-risk': typeof AppInsightGrowthRiskRoute
  '/app/insight/ranking-risk': typeof AppInsightRankingRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/profile-setup': typeof AppProfileSetupRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/users': typeof AppUsersRoute
  '/app/dashboard/competitors': typeof AppDashboardCompetitorsRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/performance': typeof AppDashboardPerformanceRoute
  '/app/insight/brand-risk': typeof AppInsightBrandRiskRoute
  '/app/insight/competitive-risk': typeof AppInsightCompetitiveRiskRoute
  '/app/insight/growth-risk': typeof AppInsightGrowthRiskRoute
  '/app/insight/ranking-risk': typeof AppInsightRankingRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/profile-setup': typeof AppProfileSetupRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/users': typeof AppUsersRoute
  '/app/dashboard/competitors': typeof AppDashboardCompetitorsRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/performance': typeof AppDashboardPerformanceRoute
  '/app/insight/brand-risk': typeof AppInsightBrandRiskRoute
  '/app/insight/competitive-risk': typeof AppInsightCompetitiveRiskRoute
  '/app/insight/growth-risk': typeof AppInsightGrowthRiskRoute
  '/app/insight/ranking-risk': typeof AppInsightRankingRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/profile-setup'
    | '/app/projects'
    | '/app/users'
    | '/app/dashboard/competitors'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/overview'
    | '/app/dashboard/performance'
    | '/app/insight/brand-risk'
    | '/app/insight/competitive-risk'
    | '/app/insight/growth-risk'
    | '/app/insight/ranking-risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/profile-setup'
    | '/app/projects'
    | '/app/users'
    | '/app/dashboard/competitors'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/overview'
    | '/app/dashboard/performance'
    | '/app/insight/brand-risk'
    | '/app/insight/competitive-risk'
    | '/app/insight/growth-risk'
    | '/app/insight/ranking-risk'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/profile-setup'
    | '/app/projects'
    | '/app/users'
    | '/app/dashboard/competitors'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/overview'
    | '/app/dashboard/performance'
    | '/app/insight/brand-risk'
    | '/app/insight/competitive-risk'
    | '/app/insight/growth-risk'
    | '/app/insight/ranking-risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile-setup': {
      id: '/app/profile-setup'
      path: '/profile-setup'
      fullPath: '/app/profile-setup'
      preLoaderRoute: typeof AppProfileSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insight/ranking-risk': {
      id: '/app/insight/ranking-risk'
      path: '/insight/ranking-risk'
      fullPath: '/app/insight/ranking-risk'
      preLoaderRoute: typeof AppInsightRankingRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insight/growth-risk': {
      id: '/app/insight/growth-risk'
      path: '/insight/growth-risk'
      fullPath: '/app/insight/growth-risk'
      preLoaderRoute: typeof AppInsightGrowthRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insight/competitive-risk': {
      id: '/app/insight/competitive-risk'
      path: '/insight/competitive-risk'
      fullPath: '/app/insight/competitive-risk'
      preLoaderRoute: typeof AppInsightCompetitiveRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insight/brand-risk': {
      id: '/app/insight/brand-risk'
      path: '/insight/brand-risk'
      fullPath: '/app/insight/brand-risk'
      preLoaderRoute: typeof AppInsightBrandRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/performance': {
      id: '/app/dashboard/performance'
      path: '/dashboard/performance'
      fullPath: '/app/dashboard/performance'
      preLoaderRoute: typeof AppDashboardPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/overview': {
      id: '/app/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/app/dashboard/overview'
      preLoaderRoute: typeof AppDashboardOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/dashboard': {
      id: '/app/dashboard/dashboard'
      path: '/dashboard/dashboard'
      fullPath: '/app/dashboard/dashboard'
      preLoaderRoute: typeof AppDashboardDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/competitors': {
      id: '/app/dashboard/competitors'
      path: '/dashboard/competitors'
      fullPath: '/app/dashboard/competitors'
      preLoaderRoute: typeof AppDashboardCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileSetupRoute: typeof AppProfileSetupRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppDashboardCompetitorsRoute: typeof AppDashboardCompetitorsRoute
  AppDashboardDashboardRoute: typeof AppDashboardDashboardRoute
  AppDashboardOverviewRoute: typeof AppDashboardOverviewRoute
  AppDashboardPerformanceRoute: typeof AppDashboardPerformanceRoute
  AppInsightBrandRiskRoute: typeof AppInsightBrandRiskRoute
  AppInsightCompetitiveRiskRoute: typeof AppInsightCompetitiveRiskRoute
  AppInsightGrowthRiskRoute: typeof AppInsightGrowthRiskRoute
  AppInsightRankingRiskRoute: typeof AppInsightRankingRiskRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileSetupRoute: AppProfileSetupRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppUsersRoute: AppUsersRoute,
  AppDashboardCompetitorsRoute: AppDashboardCompetitorsRoute,
  AppDashboardDashboardRoute: AppDashboardDashboardRoute,
  AppDashboardOverviewRoute: AppDashboardOverviewRoute,
  AppDashboardPerformanceRoute: AppDashboardPerformanceRoute,
  AppInsightBrandRiskRoute: AppInsightBrandRiskRoute,
  AppInsightCompetitiveRiskRoute: AppInsightCompetitiveRiskRoute,
  AppInsightGrowthRiskRoute: AppInsightGrowthRiskRoute,
  AppInsightRankingRiskRoute: AppInsightRankingRiskRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
