/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProfileSetupRouteImport } from './routes/app.profile-setup'
import { Route as AppBrandsRouteImport } from './routes/app.brands'
import { Route as AppInsightRiskIntelligenceRouteImport } from './routes/app.insight.risk-intelligence'
import { Route as AppInsightMarketDynamicRouteImport } from './routes/app.insight.market-dynamic'
import { Route as AppDashboardPerformanceRouteImport } from './routes/app.dashboard.performance'
import { Route as AppDashboardOverviewRouteImport } from './routes/app.dashboard.overview'
import { Route as AppDashboardDashboardRouteImport } from './routes/app.dashboard.dashboard'
import { Route as AppDashboardCompetitorsRouteImport } from './routes/app.dashboard.competitors'
import { Route as AppDashboardBrandImpressionRouteImport } from './routes/app.dashboard.brand-impression'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSetupRoute = AppProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightRiskIntelligenceRoute =
  AppInsightRiskIntelligenceRouteImport.update({
    id: '/insight/risk-intelligence',
    path: '/insight/risk-intelligence',
    getParentRoute: () => AppRoute,
  } as any)
const AppInsightMarketDynamicRoute = AppInsightMarketDynamicRouteImport.update({
  id: '/insight/market-dynamic',
  path: '/insight/market-dynamic',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardPerformanceRoute = AppDashboardPerformanceRouteImport.update({
  id: '/dashboard/performance',
  path: '/dashboard/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardOverviewRoute = AppDashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardDashboardRoute = AppDashboardDashboardRouteImport.update({
  id: '/dashboard/dashboard',
  path: '/dashboard/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardCompetitorsRoute = AppDashboardCompetitorsRouteImport.update({
  id: '/dashboard/competitors',
  path: '/dashboard/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardBrandImpressionRoute =
  AppDashboardBrandImpressionRouteImport.update({
    id: '/dashboard/brand-impression',
    path: '/dashboard/brand-impression',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/brands': typeof AppBrandsRoute
  '/app/profile-setup': typeof AppProfileSetupRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/users': typeof AppUsersRoute
  '/app/dashboard/brand-impression': typeof AppDashboardBrandImpressionRoute
  '/app/dashboard/competitors': typeof AppDashboardCompetitorsRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/performance': typeof AppDashboardPerformanceRoute
  '/app/insight/market-dynamic': typeof AppInsightMarketDynamicRoute
  '/app/insight/risk-intelligence': typeof AppInsightRiskIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/brands': typeof AppBrandsRoute
  '/app/profile-setup': typeof AppProfileSetupRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/users': typeof AppUsersRoute
  '/app/dashboard/brand-impression': typeof AppDashboardBrandImpressionRoute
  '/app/dashboard/competitors': typeof AppDashboardCompetitorsRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/performance': typeof AppDashboardPerformanceRoute
  '/app/insight/market-dynamic': typeof AppInsightMarketDynamicRoute
  '/app/insight/risk-intelligence': typeof AppInsightRiskIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/brands': typeof AppBrandsRoute
  '/app/profile-setup': typeof AppProfileSetupRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/users': typeof AppUsersRoute
  '/app/dashboard/brand-impression': typeof AppDashboardBrandImpressionRoute
  '/app/dashboard/competitors': typeof AppDashboardCompetitorsRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/performance': typeof AppDashboardPerformanceRoute
  '/app/insight/market-dynamic': typeof AppInsightMarketDynamicRoute
  '/app/insight/risk-intelligence': typeof AppInsightRiskIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/brands'
    | '/app/profile-setup'
    | '/app/projects'
    | '/app/users'
    | '/app/dashboard/brand-impression'
    | '/app/dashboard/competitors'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/overview'
    | '/app/dashboard/performance'
    | '/app/insight/market-dynamic'
    | '/app/insight/risk-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/brands'
    | '/app/profile-setup'
    | '/app/projects'
    | '/app/users'
    | '/app/dashboard/brand-impression'
    | '/app/dashboard/competitors'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/overview'
    | '/app/dashboard/performance'
    | '/app/insight/market-dynamic'
    | '/app/insight/risk-intelligence'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/brands'
    | '/app/profile-setup'
    | '/app/projects'
    | '/app/users'
    | '/app/dashboard/brand-impression'
    | '/app/dashboard/competitors'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/overview'
    | '/app/dashboard/performance'
    | '/app/insight/market-dynamic'
    | '/app/insight/risk-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile-setup': {
      id: '/app/profile-setup'
      path: '/profile-setup'
      fullPath: '/app/profile-setup'
      preLoaderRoute: typeof AppProfileSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brands': {
      id: '/app/brands'
      path: '/brands'
      fullPath: '/app/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insight/risk-intelligence': {
      id: '/app/insight/risk-intelligence'
      path: '/insight/risk-intelligence'
      fullPath: '/app/insight/risk-intelligence'
      preLoaderRoute: typeof AppInsightRiskIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insight/market-dynamic': {
      id: '/app/insight/market-dynamic'
      path: '/insight/market-dynamic'
      fullPath: '/app/insight/market-dynamic'
      preLoaderRoute: typeof AppInsightMarketDynamicRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/performance': {
      id: '/app/dashboard/performance'
      path: '/dashboard/performance'
      fullPath: '/app/dashboard/performance'
      preLoaderRoute: typeof AppDashboardPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/overview': {
      id: '/app/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/app/dashboard/overview'
      preLoaderRoute: typeof AppDashboardOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/dashboard': {
      id: '/app/dashboard/dashboard'
      path: '/dashboard/dashboard'
      fullPath: '/app/dashboard/dashboard'
      preLoaderRoute: typeof AppDashboardDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/competitors': {
      id: '/app/dashboard/competitors'
      path: '/dashboard/competitors'
      fullPath: '/app/dashboard/competitors'
      preLoaderRoute: typeof AppDashboardCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/brand-impression': {
      id: '/app/dashboard/brand-impression'
      path: '/dashboard/brand-impression'
      fullPath: '/app/dashboard/brand-impression'
      preLoaderRoute: typeof AppDashboardBrandImpressionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrandsRoute: typeof AppBrandsRoute
  AppProfileSetupRoute: typeof AppProfileSetupRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppDashboardBrandImpressionRoute: typeof AppDashboardBrandImpressionRoute
  AppDashboardCompetitorsRoute: typeof AppDashboardCompetitorsRoute
  AppDashboardDashboardRoute: typeof AppDashboardDashboardRoute
  AppDashboardOverviewRoute: typeof AppDashboardOverviewRoute
  AppDashboardPerformanceRoute: typeof AppDashboardPerformanceRoute
  AppInsightMarketDynamicRoute: typeof AppInsightMarketDynamicRoute
  AppInsightRiskIntelligenceRoute: typeof AppInsightRiskIntelligenceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrandsRoute: AppBrandsRoute,
  AppProfileSetupRoute: AppProfileSetupRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppUsersRoute: AppUsersRoute,
  AppDashboardBrandImpressionRoute: AppDashboardBrandImpressionRoute,
  AppDashboardCompetitorsRoute: AppDashboardCompetitorsRoute,
  AppDashboardDashboardRoute: AppDashboardDashboardRoute,
  AppDashboardOverviewRoute: AppDashboardOverviewRoute,
  AppDashboardPerformanceRoute: AppDashboardPerformanceRoute,
  AppInsightMarketDynamicRoute: AppInsightMarketDynamicRoute,
  AppInsightRiskIntelligenceRoute: AppInsightRiskIntelligenceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
